#!/usr/bin/env node

// http://danger.systems/js/
// https://github.com/conventional-changelog/standard-version
// https://github.com/semantic-release/semantic-release
// https://github.com/sindresorhus/np
// https://github.com/zeit/release
// https://github.com/shipitjs/shipit-deploy
// https://github.com/shinnn/gulp-gh-pages
//
// https://github.com/c4milo/github-release  // GO 语言

// 首次 push 到 github 时：
//    启用依赖更新提醒： greenkeeper enable
//    启用安全检查：     https://snyk.io
//
// 测试集成  https://github.com/philipwalton/easy-sauce， 可以参考 https://philipwalton.com/articles/learning-how-to-set-up-automated-cross-browser-javascript-unit-testing/

// 发布前可以用 irish-pub 模块来检查要发布的文件
//
/*

when you land commits on your master branch, select the Squash and Merge option.
add a title and body that follows the conventional-changelog-standard conventions.

when you're ready to release to npm:
  git checkout master; git pull origin master
  run npm test
  run standard-version
  git push --follow-tags origin master; npm publish

*/

/*
standard-version does the following:

  bumps the version in package.json (based on your commit history)
  uses conventional-changelog to update CHANGELOG.md
  commits package.json and CHANGELOG.md
  tags a new release
*/
